services:
  - type: web
    name: vs-wordle
    env: node
    buildCommand: npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
